dependencies = []
description = "Repository of GitHub Actions of the organisation"
flags = ["tools"]
languages = ["GitHub Action", "shell", "YAML"]
owner = "etienne@scalingo.com"
team = "IST"
version = "1.1.2"
